#!/bin/bash
#
#  youtube2org. Convert in orgmode and Markdown syntax, a YouTube video in image with link
#
# Copyright (C) 2019 Angel. uGeek
# ugeekpodcast@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#


if [ $1 = "-h" ]
then
echo "
youtube2org

Convert video from youtube in url orgmode
example:  youtube2org [youtube_url]  

Convert video from youtube in url Markdown
example:  youtube2org -m [youtube_url]  


More info:
https://github.com/uGeek/youtube2org
"
else  
if [ $1 = "-m" ]
then
IMAGE=$(echo $2 | cut -d "=" -f2 | cut -d "&" -f1)
echo '[![](http://img.youtube.com/vi/'$IMAGE'/0.jpg)]('$2' "")'
else
IMAGE=$(echo $1 | cut -d "=" -f2 | cut -d "&" -f1)
echo '[['$1'][http://img.youtube.com/vi/'$IMAGE'/0.jpg]]'
fi
fi

